export enum Category {
	BOOK_TRAVEL = "Book Travel",
	CHECK_IN = "Check in",
	FEES_POLICIES = "Fees Policies",
	FLIGHT_STATUS = "Flight Status",
	TICKETS = "Tickets",
	TICKETING = "Ticketing",
	AMENITIES = "Amenities",
	RESERVE = "Reserve",
	FRONT_DESK = "Front Desk",
	PARKING = "Parking",
	GIFT_CARD = "Gift Card",
	WAITLIST = "Waitlist",
	DELIVERY = "Delivery (Restaurant)",
	ORDER = "Order (Restaurant)",
	TAKEOUT = "Takeout",
	PICKUP = "Pickup (Restaurant)",
	RESERVE = "Reserve (Restaurant)",
	MENU = "Menu",
	APPOINTMENT = "Appointment",
	PORTFOLIO = "Portfolio",
	QUOTE = "Quote",
	SERVICES = "Services (Retail)",
	STORE_ORDERS = "Store Orders",
	STORE_SHOP = "Store Shop",
	STORE_SUPPORT = "Store Support",
	SCHEDULE = "Schedule",
	SHOWTIMES = "Showtimes",
	AVAILABILITY = "Availability",
	PRICING = "Pricing",
	ACTIVITIES = "Activities",
	BOOK = "Book",
	BOOK__HOTEL_ = "Book (Hotel)",
	BOOK__RIDE_ = "Book Ride",
	BOOK__TOUR_ = "Book Tour",
	CAREERS = "Careers",
	CHARGE = "Charge",
	COUPONS = "Coupons",
	DELIVERY__RETAIL_ = "Delivery (Retail)",
	DONATE = "Donate",
	EVENTS = "Events",
	ORDER__RETAIL_ = "Order (Retail)",
	OTHER_MENU = "Other Menu",
	PICKUP__RETAIL_ = "Pickup (Retail)",
	RESERVE__PARKING_ = "Reserve (Parking)",
	SHOWS = "Shows",
	SPORTS = "Sports",
	SUPPORT = "Support",
	TEE_TIME = "Tee Time",
	GIFT_CARD__RESTAURANT_ = "Gift Card (Restaurant)",
}

export interface AppleActionLinks {
	category: Category,
	appStoreUrl: string,
	quickLinkUrl: string,
	appName: string,
}

export interface ImageThumbnail {
	url: string,
	width: number,
	height: number,
}

export interface Image {
	url: string,
	width: number,
	height: number,
	thumbnails?: ImageThumbnail[],
	alternateText?: string,
}

export interface Interval {
	start?: any,
	end?: any,
}

export interface DayHour {
	openIntervals?: Interval[],
	isClosed?: boolean,
}

export interface HolidayHours {
	date: string,
	openIntervals?: Interval[],
	isClosed?: boolean,
	isRegularHours?: boolean,
}

export interface Hours {
	monday?: DayHour,
	tuesday?: DayHour,
	wednesday?: DayHour,
	thursday?: DayHour,
	friday?: DayHour,
	saturday?: DayHour,
	sunday?: DayHour,
	holidayHours?: HolidayHours[],
	reopenDate?: string,
}

export interface Address {
	line1?: string,
	line2?: string,
	line3?: string,
	sublocality?: string,
	city?: string,
	region?: string,
	postalCode?: string,
	extraDescription?: string,
	countryCode?: string,
}

export interface ComplexImage {
	image: Image,
	details?: string,
	description?: string,
	clickthroughUrl?: string,
}

export interface Coordinate {
	latitude?: number,
	longitude?: number,
}

export interface Specialty {
	entityId: string,
	name: string,
	c_synonyms?: string[],
	c_relatedConditions?: Conditions[],
	c_relatedProcedures?: Procedures[],
	c_relatedReasonsForVisit?: ReasonsForVisit[],
}

export interface Conditions {
	entityId: string,
	name: string,
	c_synonyms?: string[],
}

export interface Procedures {
	entityId: string,
	name: string,
	c_synonyms?: string[],
}

export interface ReasonsForVisit {
	entityId: string,
	name: string,
	c_synonyms?: string[],
}

export interface Bios {
	label?: string,
	ids?: string[],
}

export interface ProductLists {
	label?: string,
	ids?: string[],
}

export enum Type {
	FELLOWSHIP = "Fellowship",
	RESIDENCY = "Residency",
	INTERNSHIP = "Internship",
	MEDICAL_SCHOOL = "Medical School",
}

export interface EducationList {
	type: Type,
	institutionName: string,
	yearCompleted: number,
}

export interface FeaturedMessage {
	description?: string,
	url?: string,
}

export enum Gender {
	UNSPECIFIED = "Unspecified",
	FEMALE = "Female",
	MALE = "Male",
}

export enum Degrees {
	ANP = "Adult Nurse Practitioner (ANP)",
	APN = "Advanced Practice Nurse (APN)",
	APRN = "Advanced Practice Registered Nurse (APRN)",
	ARNP = "Advanced Registered Nurse Practitioner (ARNP)",
	AUD = "Audiologist (AUD)",
	BSW = "Bachelors of Social Work (BSW)",
	CCCA = "Certificate of Clinical Competence in Audiology (CCCA)",
	CNM = "Certified Nurse Midwife (CNM)",
	CNP = "Certified Nurse Practitioner (CNP)",
	CNS = "Clinical Nurse Specialist (CNS)",
	CPNP = "Certified Pediatric Nurse Practitioner (CPNP)",
	CRNA = "Certified Registered Nurse Anesthetist (CRNA)",
	CRNP = "Certified Registered Nurse Practitioner (CRNP)",
	DC = "Doctor of Chiropractic (DC)",
	DDS = "Doctor of Dental Surgery (DDS)",
	DMD = "Doctor of Dental Medicine (DMD)",
	DNP = "Doctor of Nursing Practice (DNP)",
	DO = "Doctor of Osteopathy (DO)",
	DPM = "Doctor of Podiatric Medicine (DPM)",
	DSW = "Doctorate Social Work (DSW)",
	DVM = "Doctor of Veterinary Medicine (DVM)",
	FNP = "Family Nurse Practitioner (FNP)",
	GNP = "Geriatric Nurse Practitioner (GNP)",
	LAC = "Licensed Acupuncturist (LAC)",
	LCSW = "Licensed Social Worker (LCSW)",
	LPN = "Licensed Practical Nurse (LPN)",
	MBA = "Master of Business Administration (MBA)",
	MBBS = "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
	MD = "Medical Doctor (MD)",
	MPH = "Master of Public Health (MPH)",
	MSW = "Master Social Work (MSW)",
	ND = "Naturopathic Doctor (ND)",
	NNP = "Neonatal Nurse Practitioner (NNP)",
	NP = "Nurse Practitioner (NP)",
	OD = "Doctor of Optometry (OD)",
	PA = "Physician Assistant (PA)",
	PAC = "Physician Assistant Certified (PAC)",
	PHARMD = "Doctor of Pharmacy (PHARMD)",
	PHD = "Doctor of Philosophy (PHD)",
	PNP = "Pediatric Nurse Practitioner (PNP)",
	PSYD = "Doctor of Psychology (PSYD)",
	RD = "Registered Dietician (RD)",
	RSW = "Registered Social Worker (RSW)",
	VMD = "Veterinary Medical Doctor (VMD)",
	WHNP = "Womens Health Nurse Practitioner (WHNP)",
}

export enum LocationType {
	LOCATION = "Location",
	HEALTHCARE_FACILITY = "Healthcare Facility",
	HEALTHCARE_PROFESSIONAL = "Healthcare Professional",
	ATM = "ATM",
	RESTAURANT = "Restaurant",
	HOTEL = "Hotel",
}

export interface MenuUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface OrderUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export enum PaymentOptions {
	ALIPAY = "Alipay",
	AMERICANEXPRESS = "American Express",
	ANDROIDPAY = "Google Pay",
	APPLEPAY = "Apple Pay",
	ATM = "ATM",
	ATMQUICK = "ATM Quick",
	BACS = "BACS",
	BANCONTACT = "Bancontact",
	BANKDEPOSIT = "Bank Deposit",
	BANKPAY = "Bank Pay",
	BGO = "Bank/Giro Overschrijving",
	BITCOIN = "Bitcoin",
	Bar = "Bargeld",
	CARTASI = "CartaSi",
	CASH = "Cash",
	CCS = "CCS",
	CHECK = "Check",
	CONB = "Contactloos betalen",
	CVVV = "Cadeaubon/VVV bon",
	DEBITNOTE = "Debit Note",
	DINERSCLUB = "Diners Club",
	DIRECTDEBIT = "Direct Debit",
	DISCOVER = "Discover",
	ECKARTE = "Girokarte",
	ECOCHEQUE = "EcoCheque",
	EKENA = "E-kena",
	EMV = "Elektronische Maaltijdcheques",
	FINANCING = "Financing",
	GOPAY = "GoPay",
	HAYAKAKEN = "Hayakaken",
	HEBAG = "He-Bag",
	IBOD = "iBOD",
	ICCARDS = "IC Cards",
	ICOCA = "Icoca",
	ID = "iD",
	IDEAL = "iDeal",
	INCA = "Incasso",
	INVOICE = "Invoice",
	JCB = "JCB",
	JCoinPay = "J−Coin Pay",
	JKOPAY = "JKO Pay",
	KITACA = "Kitaca",
	KLA = "Klantenkaart",
	KLARNA = "Klarna",
	LINEPAY = "LINE Pay",
	MAESTRO = "Maestro",
	MANACA = "Manaca",
	MASTERCARD = "MasterCard",
	MIPAY = "Mi Pay",
	MONIZZE = "Monizze",
	MPAY = "MPay",
	Manuelle_Lastsch = "Manuelle Lastschrift",
	Merpay = "メルPay",
	NANACO = "nanaco",
	NEXI = "Nexi",
	NIMOCA = "Nimoca",
	OREM = "Onder Rembours",
	PASMO = "Pasmo",
	PAYBACKPAY = "Payback Pay",
	PAYBOX = "Paybox",
	PAYCONIQ = "Payconiq",
	PAYPAL = "PayPal",
	PAYPAY = "PayPay",
	PAYSEC = "PaySec",
	PIN = "PIN",
	POSTEPAY = "Postepay",
	QRCODE = "QR Code Payment",
	QUICPAY = "QUICPay",
	RAKUTENEDY = "Rakuten Edy",
	RAKUTENPAY = "楽天Pay",
	SAMSUNGPAY = "Samsung Pay",
	SODEXO = "Sodexo",
	SUGOCA = "Sugoca",
	SUICA = "Suica",
	SWISH = "Swish",
	TICKETRESTAURANT = "Ticket Restaurant",
	TOICA = "Toica",
	TRAVELERSCHECK = "Traveler's Check",
	TSCUBIC = "TS CUBIC",
	TWINT = "Twint",
	UNIONPAY = "China UnionPay",
	VEV = "Via een verzekering",
	VISA = "Visa",
	VISAELECTRON = "Visa Electron",
	VOB = "Vooruit betalen",
	VOUCHER = "Voucher",
	VPAY = "V PAY",
	WAON = "WAON",
	WECHATPAY = "WeChat Pay",
	WIRETRANSFER = "Wire Transfer",
	Yucho_Pay = "ゆうちょPay",
	ZELLE = "Zelle",
	AuPay = "auPay",
	DBarai = "d払い ",
	Überweisung = "Banküberweisung",
}

export interface ReservationUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface WebsiteUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface ComplexVideo {
	url: string,
	video?: string,
	description?: string,
}

export default interface HealthcareProfessional {
	appleActionLinks?: AppleActionLinks[],
	appleBusinessDescription?: string,
	appleBusinessId?: string,
	appleBusinessIdDqe?: string,
	appleCompanyId?: string,
	appleCompanyIdDqe?: string,
	appleCoverPhoto?: Image,
	bingWebsiteOverride?: string,
	covid19InformationUrl?: string,
	covidMessaging?: string,
	facebookWebsiteOverride?: string,
	geomodifier?: string,
	holidayHoursConversationEnabled?: boolean,
	landingPageUrl?: string,
	linkedInUrl?: string,
	neighborhood?: string,
	nudgeEnabled?: boolean,
	onlineServiceHours?: Hours,
	primaryConversationContact?: any,
	reviewResponseConversationEnabled?: boolean,
	slug?: string,
	telehealthUrl?: string,
	what3WordsAddress?: string,
	yelpWebsiteOverride?: string,
	acceptingNewPatients?: boolean,
	additionalHoursText?: string,
	address: Address,
	addressHidden?: boolean,
	alternatePhone?: any,
	associations?: string[],
	brands?: string[],
	description?: string,
	hours?: Hours,
	logo?: ComplexImage,
	name: string,
	categories?: any,
	certifications?: string[],
	cityCoordinate?: Coordinate,
	closed?: boolean,
	clusterIndex?: number,
	conditionsTreated?: string[],
	c_specialty?: Specialty[],
	displayCoordinate?: Coordinate,
	dropoffCoordinate?: Coordinate,
	bios?: Bios,
	productLists?: ProductLists,
	educationList?: EducationList[],
	emails?: string[],
	facebookEmail?: string,
	facebookPageUrl?: string,
	fax?: any,
	featuredMessage?: FeaturedMessage,
	firstName?: string,
	photoGallery?: ComplexImage[],
	gender?: Gender,
	geocodedCoordinate?: Coordinate,
	googleWebsiteOverride?: string,
	headshot?: Image,
	admittingHospitals?: string[],
	degrees?: Degrees[],
	insuranceAccepted?: string[],
	instagramHandle?: string,
	isClusterPrimary?: boolean,
	isoRegionCode?: string,
	keywords?: string[],
	languages?: string[],
	lastName?: string,
	localPhone?: any,
	locationType?: LocationType,
	mainPhone?: any,
	menuUrl?: MenuUrl,
	middleName?: string,
	mobilePhone?: any,
	npi?: string,
	officeName?: string,
	orderUrl?: OrderUrl,
	paymentOptions?: PaymentOptions[],
	phones?: any,
	pickupCoordinate?: Coordinate,
	reservationUrl?: ReservationUrl,
	routableCoordinate?: Coordinate,
	services?: string[],
	shortName35?: string,
	shortName64?: string,
	id: string,
	timezone?: any,
	tollFreePhone?: any,
	ttyPhone?: any,
	twitterHandle?: string,
	walkableCoordinate?: Coordinate,
	websiteUrl?: WebsiteUrl,
	yearEstablished?: number,
	yextDisplayCoordinate?: Coordinate,
	yextDropoffCoordinate?: Coordinate,
	yextPickupCoordinate?: Coordinate,
	yextRoutableCoordinate?: Coordinate,
	yextWalkableCoordinate?: Coordinate,
	videos?: ComplexVideo[],
}
